### ISSUE TITLE
[BUG] tauri-port: Callbacks not working

### ISSUE THREAD

**Issue by LucasOe** [denBot/yasb#101]
## Expected Behavior
A widget with the following config should open the explorer when clicked on:
```yaml
test:
  kind: CustomWidget
  label: "Test Widget"
  callbacks:
    on_left: { exec: { cmd: "cmd.exe", args: ["/c", "explorer"] } }
```

The `toggle_label` callback works as intended, but I can't open the json_viewer, calender, nor can I execute commands.

## Current Behavior
Callbacks on_left and on_right in a custom widget do nothing. For some reason right clicking on the active program opens a browser tab as intended, other left and right click interactions do nothing. I can't open the calendar or json viewer.

## Steps to Reproduce
The issue is reproducible with the default config or the custom widget above.

## Context (Environment)
I'm running my own build of the tauri-port without any modifications. Using Windows 10 22H2.

The log file shows the following errors on left click:
```
00:20:19 [WARN] RedrawEventsCleared emitted without explicit MainEventsCleared
00:21:10 [WARN] NewEvents emitted without explicit RedrawEventsCleared
```
