### ISSUE TITLE
[BUG] Bar padding behavior

### ISSUE THREAD

**Issue by Vernetzt** [denBot/yasb#12]
## Expected Behavior
top changes the top
left changes left
bottom changes the bottom
right changes the right

## Current Behavior
top changes the top and right?
left changes the bottom?
bottom changes the bottom and right?
right changes the bottom?

## Context (Environment)
This could be me misunderstanding the use of these settings but my assumption would be that changing the top padding to say `top: 10` would pad the bar 10 pixels from the top of the screen it was created on. As it stands now doing so seems to do that but also pad the the bar on the right side by the same value. Similar problems exist for left/bottom/right as stated above.

yasb - [c03f296](https://github.com/denBot/yasb/commit/c03f29605727d722649bdc4b8b8a5b360bee60da)
Windows 11 - 22000.438

## Example
```
bars:
  yasb-bar:
    alignment:
      position: "top"
      center: true
    dimensions:
      width: "100%"
      height: 25
    padding:
      top: 10
      left: 0
      bottom: 0
      right: 0
```
Image showing the top left and right corners with pixel rulers in red.
![yasb-corners](https://user-images.githubusercontent.com/8786961/152658381-8c4e1210-316a-42f2-9498-60c44aa24687.png)
