### ISSUE TITLE
explain to me what i need to do to create a new custom executable widget

### ISSUE THREAD

**Issue by XxnittanixX** [denBot/yasb#23]
i want to run google from the bar  how would i get a  widget  to  show up with just plain text   i want to click on the word chrome and it run chrome.exe or custom file path  how would i go about that

**Comment by DakshG07** [comment]
@XxnittanixX it would look like this:
```  
chrome_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "Chrome"
      label_alt: "Open Chrome"
      class_name: "chrome-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec chrome.exe"
        on_right: "toggle_label"
```
