### ISSUE TITLE
[BUG] Battery widget won't allow icon changes

### ISSUE THREAD

**Issue by watatomo** [denBot/yasb#25]
## Expected Behavior
Battery status icon should change.

## Current Behavior
YASB doesn't display the battery widget and won't respond to click gestures.

## Steps to Reproduce
1. Add `status_icons` to `config.yml`.

```
widgets:
    battery:
        type: "yasb.battery.BatteryWidget"
        options:
            time_remaining_natural: true
            label: "{icon} {percent}"
            label_alt: "remaining: {time_remaining}"
            update_interval: 1000
            charging_options:
                icon_format: "{icon}"
                blink_charging_icon: false
            status_thresholds:
                critical: 10
                low: 30
                medium: 60
                high: 80
                full: 100
            status_icons:
                charging: "\uf583"
                critical: "\uf579"
                low: "\uf57b"
                medium: "\uf57e"
                high: "\uf580"
                full: "\uf578"
            callbacks:
                on_left: "toggle_label"
                on_middle: "do_nothing"
                on_right: "do_nothing"
```

## Context (Environment)
Log: [yasb.log](https://github.com/denBot/yasb/files/9125618/yasb.log)
Config: [config.yml](https://gist.github.com/watatomo/c04b03628223e17cd839baf5327e669e)
Running on Windows 11 22H2.
