### ISSUE TITLE
[BUG] Active window widget broken

### ISSUE THREAD

**Issue by pulpocaminante** [denBot/yasb#67]
The window title widget should be working by default, I assume, but it is not. Komorebi is correctly connected, the window title widget is enabled, and the options are set to their default values in config.yaml. We have no errors or warnings being printed by main.py.

The widget fails to appear entirely, unless we set `label_no_window`, in which case it will flash briefly on startup before disappearing within 100ms or so.

I've tried running it in both a normal and elevated prompt.

As for reproduction, I'm not really sure since this is just using all of the default settings.

All of the fonts are installed correctly and every other widget is working as expected.

**Comment by TooSpooky** [comment]
Hello,

I'm also experiencing this issue as well.

**Comment by theokkstar** [comment]
What fixed this for me was setting the the option `monitor_exclusive` to `false` within `config.yaml`:
```yaml
widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: false
```
