### ISSUE TITLE
[BUG] Not falling back to next font in font-family

### ISSUE THREAD

**Issue by lsgalante** [denBot/yasb#94]
## Expected Behavior
Widgets should display icons properly

## Current Behavior
Widgets only recognize first font defined in styles.css defined in font-family

## Steps to Reproduce
I can reproduce this issue simply by running yasb with all default configurations.

## Context (Environment)
I am not very experience with this kind of thing and hope I am not missing something foolish.
[yasb.log](https://github.com/denBot/yasb/files/11654434/yasb.log)

**Comment by theokkstar** [comment]
I'm having this issue too on the default configuration. Has anyone been able to solve it?

**Comment by Chat-mots** [comment]
Same issue here. Could not find where the problem was.

**Comment by tmstorm** [comment]
After looking into this a little more it seams like an issue with Font Awesome and the way it is being called. Bars is being used as a fall back font for the CPU monitor and will show the correct glyphs. However I did find that the default config.yaml is using the incorrect Unicode for the [Bars](https://github.com/and3rson/graph-bars-font/blob/master/README.md) font.

If you update your config.yaml to this it should render the correct glyphs for the CPU bars.
``` css 
 cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\uf200 {info[histograms][cpu_percent]}"
      label_alt: "\uf200 CPU: {info[percent][total]}% | freq: {info[freq][current]:.2f} Mhz"
      update_interval: 500
      histogram_icons:
        - '\u3000' # 0%
        - '\u3001' # 10%
        - '\u3002' # 20%
        - '\u3003' # 30%
        - '\u3004' # 40%
        - '\u3005' # 50%
        - '\u3006' # 60%
        - '\u3007' # 70%
        - '\u3008' # 80%+
      histogram_num_columns: 10
```

**Comment by Chat-mots** [comment]
@tmstorm can confirm, It is correctly falling back to the font Bars. And it is probably not a problem of dependencies : I am using all requirements from requirements.txt at their latest version, thinking it could correct the issue, but nothing changed. 
So is the problem coming from the font itself ? I've tried with Font Awesome v5 and v6 and same issue, icons are not displayed.

**Comment by tmstorm** [comment]
@Chat-mots I think you are on to something here. If you move 'Font Awesome 5 Free' to the front of the list you will notice that the text font changes but still will not apply the glyphs. 

``` css
font-family:  'Font Awesome 5 Free', 'Courier New', 'Bars'; /* Nothing will work */
```

However if I change it to 'Font Awesome 5 Free Solid' it will show the glyphs but not fall back to Courier New or Bars fonts. This is expected since the order matters and Font Awesome has a text font so there will be no fallback used.

``` css
font-family:  'Font Awesome 5 Free Solid', 'Courier New', 'Bars'; /* This will show glyphs but not use fallbacks */
```

The use is that if you place it back at the end and add 'Solid' it still will not work.  
``` css
font-family:  'Courier New', 'Bars', 'Font Awesome 5 Free Solid'; /* This will not work */
```

**Comment by tmstorm** [comment]
I fixed the issue for myself but it required changing the core code. I use waybar on Arch also and waybar separates icons and labels. So I modified the code to add an icon field and class for css then added it to the json validation. Once I did that I update my styles.css with the below code and all fonts and glyphs now show correctly. 

```css
.cpu-widget .icon { 
    font-family: 'Font Awesome 4 Free';
    font-weight: 900; /* This is required since the glyphs are in the Solid variant of Font Awesome */
    font-size: 14px;
}
```

My change is a work around but I do think the content of each widget should be changed to be more modular to give the user the option to call icons as an independent option.

I haven't posted all the code I added to the core since I had to change every widget. Including the custom widget and their corresponding validation files.
